services:
  - type: web
    name: chaz-backend
    runtime: node
    repo: https://github.com/Ssiyam0123/chatz
    branch: main
    rootDir: backend-pg
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false # User will input their Neon DB URL directly in Render
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: CORS_ORIGIN
        value: "*"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
